{
"SendMessage":2,
"MyMessage":
"Welcome and Enjoy!
 \n PrivateVpn Pro
\n- GTM NO LOAD
\n- STS NO LOAD
\n- PROMONET ( NO BLOCK ) 
\n- GIGA STORIES PWEDE NA SA TIKTOK BASED PROMO
\n- GTM NO LOAD IBA IBANG PAYLOAD YAN PER NO. AND THEN IP HUNT MUNA AND CONNECT THANKS"}
